"""set product slug as unique

Revision ID: 31644831b386
Revises: 0af1d4a634c1
Create Date: 2026-02-06 15:20:07.846110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31644831b386'
down_revision: Union[str, Sequence[str], None] = '0af1d4a634c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_db', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'product_db', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_db', type_='unique')
    op.alter_column('category_db', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
